#!/usr/bin/env bash
# Displays the content of the file /etc/passwd
# Display username, user id, user's home directory path

while read -r passwd;
do
	echo "$passwd" | cut -d ':' -f 1,3,6
done < "/etc/passwd"
